Change favicons
hspsh/hsp.sh pull request #117
Opened 2020-10-19 20:29 UTC by not7cd

2020-10-19 20:37 UTC, yasiupl requested changes

2020-10-19 20:37 UTC, yasiupl commented on favicon/site.webmanifest
> +            "src": "android-chrome-192x192.png",
This resource doesn't exist. add /favicon/ to the src.

2020-10-19 20:37 UTC, yasiupl commented on favicon/site.webmanifest
> +            "src": "android-chrome-256x256.png",
The same applies here.

2020-10-19 20:37 UTC, yasiupl commented on _layouts/meta.html
> +    <link rel="manifest" href="/favicon/site.webmanifest">
Now we have two manifest files. Remove one and edit the other to reflect the changes.

2020-10-20 12:37 UTC, not7cd commented
good to go

2020-10-20 12:38 UTC, merged

2020-10-20 12:39 UTC, yasiupl commented
Cool, Now do DNS